# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255, verbose_name='IP')),
                ('port', models.CharField(max_length=255, verbose_name='端口')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('type', models.CharField(help_text='只支持Oracle数据库', max_length=255, verbose_name='数据库')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('table', models.CharField(help_text='Oracle下的数据表', max_length=255, verbose_name='数据表')),
                ('lastid', models.IntegerField(verbose_name='检测ID')),
                ('speed', models.IntegerField(verbose_name='检测速度')),
            ],
            options={
                'verbose_name': '检测配置',
                'verbose_name_plural': '检测配置',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='testresult',
            name='is_target',
            field=models.BooleanField(default=False, verbose_name='是否目标'),
        ),
    ]
