# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testappp', '0002_auto_20170711_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrule',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
